# Pre Prosesing

Preprocessing data adalah tahap awal dalam proses pengolahan data yang bertujuan untuk membersihkan, memperbaiki, dan menyiapkan data mentah agar siap digunakan dalam proses analisis atau data mining.

## Normalization Data

Normalisasi data adalah proses mengubah skala nilai data menjadi rentang tertentu tanpa mengubah informasi utama dari data tersebut.Dengan normalisasi, data yang memiliki nilai sangat besar tidak akan mendominasi atribut lain yang memiliki nilai kecil.

### 1. Min-Max Normalization

Min-Max Normalization digunakan untuk mengubah nilai data ke dalam rentang tertentu, biasanya 0 sampai 1.

$$ v'=\frac{v - min}{max - min} $$

contoh:

| No | Umur | IPK  | Semester |
| -- | ---- | ---- | -------- |
| 1  | 18   | 3.10 | 2        |
| 2  | 19   | 3.25 | 3        |
| 3  | 20   | 3.40 | 4        |
| 4  | 21   | 3.55 | 6        |
| 5  | 22   | 3.70 | 8        |

ipk 1
    min : 3.10
    max : 3.70

$$ v' =\frac{3.10-3.10}{3.70-3.10} = 0 $$

### 2. Z-Score Normalization

Z-score digunakan untuk menormalkan data berdasarkan rata-rata dan standar deviasi sehingga data memiliki mean = 0 dan standar deviasi = 1.

$$ v'=\frac{v - \bar{x}}{\sigma} $$

Contoh data umur:

1. mennetukan mean

$$ \bar{x} = \frac{18+19+20+21+22}{5} = 20 $$

2. menentukan standar deviasi

$$ \sigma = \sqrt{\frac{(18-20)^2 + (19-20)^2 + (20-20)^2 + (21-20)^2 + (22-20)^2}{5}
} = 1.41 $$

3. nilai z-score

$$ v' = \frac{19 - 20}{1.41} = 0.71 $$

### 3. Decimal Scaling Normalization

Decimal scaling menormalkan data dengan membagi nilai dengan pangkat 10 sehingga nilai berada pada rentang kecil.

$$ v'= \frac{v}{10^j} $$

Contoh data semester:
sebelom menghitung nilai kita tentukan terlebih dahulu untuk nilai j, yaitu jumlah digit dari nilai maksimum.
max=8 (1 digit),sehingga nilai j=1

$$ v' = \frac{2}{10^1} = 0.2 $$

## Normalisasi data menggunakan library sklearn

In [11]:
# Import Library
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

# Membuat data
data = {
    "No": [1,2,3,4,5],
    "Umur": [18,19,20,21,22],
    "IPK": [3.10,3.25,3.40,3.55,3.70],
    "Semester": [2,3,4,6,8]
}

df = pd.DataFrame(data)
df

   No  Umur   IPK  Semester
0   1    18  3.10         2
1   2    19  3.25         3
2   3    20  3.40         4
3   4    21  3.55         6
4   5    22  3.70         8

In [13]:
scaler_minmax = MinMaxScaler()

minmax = scaler_minmax.fit_transform(df[["Umur","IPK","Semester"]])

df_minmax = pd.DataFrame(minmax, columns=["Umur","IPK","Semester"])

df_minmax

   Umur   IPK  Semester
0  0.00  0.00  0.000000
1  0.25  0.25  0.166667
2  0.50  0.50  0.333333
3  0.75  0.75  0.666667
4  1.00  1.00  1.000000

In [8]:
# Normalisasi Z-Score
scaler = StandardScaler()

data_zscore = scaler.fit_transform(df[["Umur","IPK","Semester"]])

df_zscore = pd.DataFrame(data_zscore, columns=["Umur","IPK","Semester"])

df_zscore

       Umur       IPK  Semester
0 -1.414214 -1.414214 -1.207020
1 -0.707107 -0.707107 -0.742781
2  0.000000  0.000000 -0.278543
3  0.707107  0.707107  0.649934
4  1.414214  1.414214  1.578410

In [9]:
# Normalisasi Decimal Scaling
def decimal_scaling(data):
    max_val = data.abs().max()
    j = len(str(int(max_val)))
    return data / (10 ** j)

df_decimal = df[["Umur","IPK","Semester"]].apply(decimal_scaling)

df_decimal

   Umur    IPK  Semester
0  0.18  0.310       0.2
1  0.19  0.325       0.3
2  0.20  0.340       0.4
3  0.21  0.355       0.6
4  0.22  0.370       0.8